[[gravitee-devguide-policies]]
= Create a custom identity provider
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_userguide_custom_identity_provider.html
:page-folder: am/dev-guide
:page-layout: am

== Overview

You create custom identity providers in AM using _policies_.
Policies are steps in the `OnRequest` Gateway proxy chain. A policy acts as a _proxy controller_ by guaranteeing if a given business rule is fulfilled during OnRequest processing.

Let's look at an example of how to develop a custom identity provider using a policy in AM.

== Getting started

Before you start, don't forget to activate http://central.sonatype.org/pages/ossrh-guide.html[OSS repositories, window=\"_blank\"] in your https://maven.apache.org/settings.html[Maven settings, window=\"_blank\"].

== Policy skeleton generation

Imagine you want to create a policy that controls if requests contains the `X-Foo` header. Let's name it the _Foo header check policy_. Then you can generate your policy like this:

[source,bash]
----
$ mvn archetype:generate\
    -DarchetypeGroupId=io.gravitee.maven.archetypes\
    -DarchetypeArtifactId=gravitee-policy-maven-archetype\
    -DarchetypeVersion=1.8.0\
    -DartifactId=foo-header-check-policy\
    -DgroupId=my.gravitee.extension.policy\
    -Dversion=1.0.0-SNAPSHOT\
    -DpolicyName=FooHeaderCheck
----

[NOTE]
==========================
When generating a policy, choose a short but clear name for it, *without specifying the _policy_ suffix*. The `gravitee-policy-maven-archetype` will add it automatically.

For example, *do not* specify the `policyName` of your policy like this:

[source]
----
-DpolicyName=CustomIDPPolicy
----

but like this:

[source]
----
-DpolicyName=CustomIDP
----
==========================

Once executed and parameters confirmed, the above command will create the `foo-header-check-policy` directory containing the following structure:

[source]
----
.
├── pom.xml
├── README.md
└── src
    ├── assembly
    │   └── policy-assembly.xml
    ├── main
    │   ├── java
    │   │   └── my
    │   │       └── gravitee
    │   │           └── extension
    │   │               └── policy
    │   │                   ├── FooHeaderCheckPolicyConfiguration.java
    │   │                   └── FooHeaderCheckPolicy.java
    │   └── resources
    │       └── plugin.properties
    └── test
        └── java
            └── my
                └── gravitee
                    └── extension
                        └── policy
                            └── FooHeaderCheckPolicyTest.java
----

The different generated files are as follows:

|===
|File |Description

| <<bookmark-pom>> |The main Maven POM file
| <<bookmark-readme>> |The main entry point for the policy documentation
| <<bookmark-policy-assembly>> |The common Maven assembly descriptor for any policies
| <<bookmark-configuration-class>> |The policy configuration class
| <<bookmark-policy-class>> |The policy class, from which the business behavior is implemented
| <<bookmark-descriptor>> |The policy descriptor file
| <<bookmark-test>> |The policy unit test Java class
|===

[discrete]
[[bookmark-pom]]
=== pom.xml

Each policy (and more generally all Gravitee projects) are https://maven.apache.org/[Maven] managed. A policy project is described by using the Maven https://maven.apache.org/pom.html[Project Object Model] file.

[discrete]
[[bookmark-readme]]
=== README.md

Each policy should have a dedicated `README.md` file to document it. The `README.md` file should contain everything related to the use of your policy: _What is its functionality? How can you use it? How can you configure it?_

[discrete]
[[bookmark-policy-assembly]]
=== policy-assembly.xml

A policy is just a kind of Gravitee plugin.

It can be plugged into the <<gateway, AM _gateway_>> by using the distribution file built from the `policy-assembly.xml` file.

Based on our _FooHeaderCheck_ policy, the distribution file structure is as follows:

[source]
----
.
├── foo-header-check-policy-1.0.0-SNAPSHOT.jar
├── lib
└── schemas
    └── urn:jsonschema:my:gravitee:extension:policy:FooHeaderCheckPolicyConfiguration.json
----

The different generated files are as follows:

|===
|File |Description

|`foo-header-check-policy-1.0.0-SNAPSHOT.jar` |The main _policy_ jar file
|`lib/` |Where the external dependencies are stored (from the https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html[Maven POM file dependencies]
|`schemas/` |Where the JSON configuration schemas are stored
|===

[discrete]
[[bookmark-configuration-schema]]
=== JSON Configuration schemas

Policy configuration is described inside one or several http://docs.oracle.com/javase/tutorial/javabeans/[Java Bean] classes (see the <<bookmark-configuration-class>> example).

During the packaging phase, each policy configuration class is processed to generate one or several http://json-schema.org/[JSON schema(s)] that will be read by the _gateway_ when the policy is plugged in.

JSON schema generation is performed by Gravitee's https://github.com/gravitee-io/json-schema-generator-maven-plugin[json-schema-generator-maven-plugin] Maven plugin.

[discrete]
[[bookmark-configuration-class]]
=== FooHeaderCheckPolicyConfiguration.java

The policy configuration class.

Policy configuration is described in one or several http://docs.oracle.com/javase/tutorial/javabeans/[Java Bean] class(es) where each attribute is a configuration parameter.

During packaging, policy configuration is compiled into link:#schemas[JSON Configuration schemas]. These schemas are used to parse https://github.com/gravitee-io/gravitee-gateway[API definitions].

Policy configuration is injected into the policy class instance at runtime and can then be used during implementation.



[discrete]
[[bookmark-descriptor]]
=== plugin.properties

As mentioned previously, a policy is a kind of Gravitee plugin. Each plugin is described by the _plugin.properties_ descriptor which declares the following parameters:

|===
|Parameter |Description |Default value

|`id` |The policy identifier |_policy_ artifact id
|`name` |The policy name |N/A (mandatory parameter)
|`version` |The policy version |N/A (mandatory parameter)
|`description` |The policy description |"Description of the _Policy name_ Gravitee Policy"
|`class` |The main policy class |Path to the generated class file
|`type` |The type of Gravitee plugin |`policy`
|===

NOTE: A policy is enabled when declared in the API definition. The policy identifier is used, as its name suggests, to identify the policy. You must ensure you choose the correct policy identifier* from the outset. It may be hard to rename it later if there are many API definitions linked to it.

[discrete]
[[bookmark-test]]
=== FooHeaderCheckPolicyTest.java

The http://junit.org/[JUnit] unit test class for this policy.
